---

ipa_server_fqdn: "idm.example.ca"
ipa_client_dns_servers: "192.168.140.5"

# These vault variables should be encrypted in your
# rhisbuilder_vault.yml file

ipa_admin_principal: "{{ ipa_admin_principal_vault }}"
ipa_admin_password: "{{ ipa_admin_password_vault }}"


# These variables get used outside of the redhat role, so are set here.

ipa_server_domain: "example.ca"
ipa_server_realm: "{{ ipa_server_domain | upper }}"

# ipaserver role variables
# Some variables deviate from our standard as they
# are specified by the redhat.rhel_idm collection
# infrequently changed variables

ipaadmin_password: "{{ ipa_admin_password }}"
ipadm_password: "{{ ipa_dm_password }}"


# Control for building platform_hosts
# There are test host lists, kvm hosts, aap hosts, container host, etc.. we build them all at different times
build_release_limit: 4  # a good number is the number of hypervisors, this should be adjusted to compensate for array write saturation.
# 30 minutes is a lot of time, but I have slow storage devices for VMs, decrease this if you have a fast array. That is usually the bottleneck.
build_release_timeout: 1800 # baremetal reliably builds in under 10 minutes - building 14 hosts at once was a non-issue.

platform_hosts:
  "{{ aap24_hosts }}"
#  "{{ bond_test_hosts }}"
#  "{{ capsule_hosts }}"
#  "{{ convert2rhel_test_hosts }}"
#  "{{ hg_test_hosts }}"
#  "{{ kvm_hypervisor_test_hosts }}
